name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy .jar 
        run: mkdir build && mv target/ScenarioQualityChecker-2.0-spring-boot.jar build/ScenarioQualityCheckerREST.jar && mv target/ScenarioQualityChecker-2.0-shaded.jar build/ScenarioQualityCheckerGUI.jar
      - uses: actions/upload-artifact@v2
        with:
          name: ScenarioQualityCheckerREST.jar
          path: build
      - name: Javadocs
        run: mvn javadoc:javadoc
      - uses: actions/upload-artifact@v2
        with:
          name: Docs
          path: target/site/apidocs
